---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  releaseName: helm-operator
  chart:
    repository: https://charts.fluxcd.io
    name: helm-operator
    version: 1.4.4
  values:
    image:
      repository: docker.artifactory.mgmt.aws.uk.tsb/docker-remote/fluxcd/helm-operator
    git:
      ssh:
        secretName: flux-git-deploy
    helm:
      versions: v3
    extraEnvs:
      - name: http_proxy
        value: http://eu-west-2.proxy.aws.uk.tsb:3128
      - name: https_proxy
        value: http://eu-west-2.proxy.aws.uk.tsb:3128
      - name: no_proxy
        value: localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.20.0.0/16,.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,ssm.eu-west-2.amazonaws.com,ssmmessages.eu-west-2.amazonaws.com,ec2.eu-west-2.amazonaws.com,ec2messages.eu-west-2.amazonaws.com,s3.eu-west-2.amazonaws.com,autoscaling.eu-west-2.amazonaws.com,secretsmanager.eu-west-2.amazonaws.com,kms.eu-west-2.amazonaws.com,ecr.eu-west-2.amazonaws.com,.eks.amazonaws.com,.ecr.eu-west-2.amazonaws.com,.s3.eu-west-2.amazonaws.com,.cluster.local,.aws.uk.tsb