resources:
  - alertmanager.yaml
  - alertmanager-sns-forwarder.yaml
  - prometheus.yaml
  - storage.yaml
  - consul-exporter.yaml
  - cloudwatch-exporter.yaml
  - prometheusrule-cb-down.yaml
  - prometheusrule-cb-up.yaml
  - prometheusrule-cb-responsetime.yaml
  - prometheusrule-rax-endpoints.yaml
  - prometheusrule-cdc-alerts.yaml
  - prometheusrule-rax-middleware.yaml
  - prometheusrule-rax-node.yaml
  - prometheusrule-itops.yaml
  - prometheusrule-datalake-alerts.yaml
  - prometheus-scylla-alerts.yaml
  - prometheusrule-ods-up.yaml
  - prometheusrule-ods-down.yaml
  - prometheusrule-ods-sys-api-down.yaml
  - prometheusrule-ods-sys-api-up.yaml
  - prometheusrule-tsb-ob-signing-down.yaml
  - 1_prometheus_cob_create_user_responsetime_alerts_rule.yaml
  - 2-prometheus_cob_verify_email_token_responsetime_alerts_rule.yaml
  - 3_prometheus_cob_send_opt_responsetime_alerts_rule.yaml
  - 4_prometheus_cob_verify_otp_responsetime_alerts_rule.yaml
  - 5_prometheus_cob_idv_get_token_responsetime_alerts_rule.yaml
  - 6_prometheus_cob_idv_get_ocr_responsetime_alerts_rule.yaml
  - 7_prometheus_cob_create_datacapture_affordability_responsetime_alerts_rule.yaml
  - 8_prometheus_cob_create_datacapture_aboutyou_responsetime_alerts_rule.yaml
  - 9_prometheus_cob_idv_get_report_responsetime_alerts_rule.yaml
  - 10_prometheus_cob_onboarding_check_user_name_responsetime_alerts_rule.yaml
  - 11_prometheus_cob_onboarding_start_responsetime_alerts_rule.yaml
  - 12_prometheus_cob_onboarding_details_responsetime_alerts_rule.yaml
  - 13_prometheus_cob_onboarding_report_responsetime_alerts_rule.yaml
  - 14_prometheus_cob_onboarding_complete_responsetime_alerts_rule.yaml
  - 15_prometheus_cob_create_state_management_responsetime_alerts_rule.yaml
  - 16_prometheus_cob_product_pricing_data_responsetime_alerts_rule.yaml
  - 17-prometheus_cob_all_pod_down_alerts_rule.yaml
  - 18-prometheus_cob_low_replca_count_alerts_rule.yaml
  - 19-prometheus_cob_pod_restarts_alerts_rule.yaml
  - 20_prometheus_cob_create_updatedownsell_responsetime_alerts_rule.yaml
  - prometheusrule-sco-fl-all-pod-down.yaml
  - prometheusrule-sco-fl-pod-restart.yaml
  - prometheusrule-sco-fl-replica-count.yaml
  - prometheusrule-sco-fl-responsetime.yaml
  - prometheusrule-sco-fl-responsetime_newurls.yaml
  - prometheusrule_sca_authentication_api_failure_rate.yaml
  - prometheusrule_sca_authentication_api_responsetime.yaml
  - prometheusrule_sca_gw_failure_rate.yaml
  - prometheusrule_sca_pod_down.yaml
  - prometheusrule_sca_pod_replica_count.yaml
  - prometheusrule_sca_pod_restart.yaml
  - prometheusrule_sca_ram_cpu_high.yaml
  - prometheusrule_sca_stepup_auth_api_failure_rate.yaml
  - prometheusrule_sca_stepup_auth_api_responsetime.yaml
  - prometheusrule_sca_transaction_query_api_failure_rate.yaml
  - prometheusrule_sca_transaction_query_api_responsetime.yaml
  - prometheusrule-cop-phase2-all-pod-down.yml
  - prometheusrule-cop-phase2-inbound-http-status.yaml
  - prometheusrule-cop-phase2-low-replica-count-all-ms.yaml
  - prometheusrule-cop-phase2-outbound-mobile-http-status.yml
  - prometheusrule-cop-phase2-outbound-onprem-http-status.yml
  - prometheusrule-cop-phase2-responsetime.yml
  - prometheusrule-cop-phase2-restart-for-all-ms.yaml
  - prometheusrule-cop-phase2-CAMIS-MS-Report_failure.yaml
  - prometheusrule-sco-fl-restproxy-api-stage1-failure-rate.yaml
  - prometheusrule-sco-fl-restproxy-api-stage2-failure-rate.yaml
  - prometheusrule-msk-alerts.yaml
namespace: prometheus
transformers:
  - awsTransformer.yaml
